# Generated by Django 4.0 on 2021-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=350, null=True, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=320, null=True)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('estate_type', models.CharField(max_length=50, null=True)),
                ('use_type', models.CharField(max_length=50, null=True)),
                ('ppm', models.PositiveIntegerField(blank=True, null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('store', models.BooleanField(blank=True, default=False, null=True)),
                ('elevator', models.BooleanField(blank=True, default=False, null=True)),
                ('image_url', models.CharField(blank=True, max_length=120, null=True)),
                ('balcon', models.BooleanField(blank=True, default=False, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('equipments', models.CharField(blank=True, max_length=350, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500)),
            ],
        ),
    ]
