# Generated by Django 4.0 on 2021-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('estate_type', models.CharField(choices=[('Apartement', 'Apa'), ('House', 'Hou'), ('Commercial', 'Com'), ('Villa', 'Vil')], default='Apartement', max_length=50)),
                ('ppm', models.IntegerField()),
                ('rooms', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
