# Generated by Django 4.0 on 2021-12-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_type',
            field=models.CharField(choices=[('Apartement', 'Apa'), ('House', 'Hou'), ('Commercial', 'Com'), ('Villa', 'Vil')], default='Apartement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='ppm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
