# Generated by Django 4.0 on 2021-12-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_estate_area_alter_estate_estate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
