# Generated by Django 4.0 on 2021-12-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_alter_estate_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_type',
            field=models.CharField(choices=[('Apartement', 'Apa'), ('House', 'Hou'), ('Commercial', 'Com'), ('Villa', 'Vil')], max_length=50, null=True),
        ),
    ]
