# Generated by Django 4.0 on 2021-12-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_estate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='ppm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
