# Generated by Django 4.0 on 2021-12-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_alter_estate_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='use_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
