# Generated by Django 4.0 on 2021-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_estate_use_type_alter_estate_estate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='store',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
