# Generated by Django 4.0 on 2021-12-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_estate_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
