# Generated by Django 4.0 on 2021-12-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0011_estate_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='image_list',
            field=models.ManyToManyField(to='estates.ImageList'),
        ),
    ]
