# Generated by Django 4.0 on 2021-12-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0012_imagelist_estate_image_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='image_list',
        ),
    ]
