# Generated by Django 4.0 on 2021-12-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0013_remove_estate_image_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image_list',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
