# Generated by Django 4.0 on 2021-12-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0015_rename_image_list_estate_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
