# Generated by Django 4.0 on 2021-12-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0016_estate_date_estate_direction_estate_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
