# Generated by Django 4.0 on 2021-12-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0017_estate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
