# Generated by Django 4.0 on 2021-12-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0018_alter_estate_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
