# Generated by Django 4.0 on 2021-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0020_estate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='equipments',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
