# Generated by Django 4.0 on 2021-12-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0021_estate_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='balcon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
